global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'appwithpostgres-monitor'
    env: 'production'

rule_files:
  # Add alerting rules here when implemented
  # - "alerting_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 30s
    scrape_timeout: 10s
    metrics_path: '/metrics'
    honor_labels: true

  # Backend API metrics
  - job_name: 'backend-api'
    static_configs:
      - targets: ['backend:5000']
    metrics_path: '/metrics'
    scrape_interval: 10s
    scrape_timeout: 5s
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: 'http_request_duration_ms_.*'
        target_label: __name__
        replacement: 'http_request_duration_seconds'
      - source_labels: [__name__]
        regex: 'nodejs_.*'
        target_label: service
        replacement: 'backend'

  # PostgreSQL Database metrics
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres_exporter:9187']
    scrape_interval: 30s
    scrape_timeout: 10s
    metrics_path: '/metrics'
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 'postgres_exporter:9187'
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: 'pg_.*'
        target_label: service
        replacement: 'postgresql'

  # Redis Cache metrics
  - job_name: 'redis'
    static_configs:
      - targets: ['redis_exporter:9121']
    scrape_interval: 30s
    scrape_timeout: 10s
    metrics_path: '/metrics'
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
      - target_label: service
        replacement: 'redis'
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: 'redis_.*'
        target_label: service
        replacement: 'redis'

  # RabbitMQ Message Queue metrics
  - job_name: 'rabbitmq'
    static_configs:
      - targets: ['rabbitmq_exporter:9419']
    scrape_interval: 30s
    scrape_timeout: 10s
    metrics_path: '/metrics'
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
      - target_label: service
        replacement: 'rabbitmq'
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: 'rabbitmq_.*'
        target_label: service
        replacement: 'rabbitmq'

  # Node Exporter (if added later for system metrics)
  # - job_name: 'node'
  #   static_configs:
  #     - targets: ['node_exporter:9100']
  #   scrape_interval: 30s
  #   scrape_timeout: 10s 